# Generated by Django 2.1.5 on 2019-01-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='author',
            new_name='author1',
        ),
    ]
