# Generated by Django 2.1.5 on 2019-01-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190108_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='author',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
