# Generated by Django 2.1.5 on 2019-01-15 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190111_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='totmarks',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
