# Generated by Django 2.1.5 on 2019-02-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_task_totmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('students', models.TextField()),
                ('tasks', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='school',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
        migrations.RemoveField(
            model_name='task',
            name='input',
        ),
        migrations.RemoveField(
            model_name='task',
            name='keyterms',
        ),
        migrations.RemoveField(
            model_name='task',
            name='output',
        ),
        migrations.AlterField(
            model_name='task',
            name='totmarks',
            field=models.CharField(max_length=200),
        ),
    ]
