# Generated by Django 2.1.5 on 2019-02-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190221_1241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Classes',
        ),
    ]
