# Generated by Django 2.1.5 on 2019-02-21 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190221_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='teachers',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
