# Generated by Django 2.1.5 on 2019-06-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_classes_teachers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Practicals',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.RenameField(
            model_name='practicals',
            old_name='students',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='practicals',
            old_name='tasks',
            new_name='subject_tag',
        ),
        migrations.RenameField(
            model_name='practicals',
            old_name='teachers',
            new_name='things_needed',
        ),
    ]
