# Generated by Django 2.1.5 on 2019-06-28 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190628_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicals',
            name='year_tag',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
