# Generated by Django 2.1.5 on 2019-06-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_years'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Practicals',
            new_name='practical',
        ),
        migrations.RenameModel(
            old_name='Years',
            new_name='year',
        ),
    ]
